# Generated by Django 3.0.5 on 2020-05-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAndTheAged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('aged_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('birth_yy', models.IntegerField()),
                ('birth_mm', models.IntegerField()),
                ('birth_dd', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('user_name', 'aged_name')},
            },
        ),
        migrations.CreateModel(
            name='TheAgedAndMedicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('aged_name', models.CharField(max_length=50)),
                ('medicament_name', models.CharField(max_length=50)),
                ('dosage', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('freq', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_name', 'aged_name', 'medicament_name')},
            },
        ),
    ]
